apiVersion: v1
entries:
  simply-dns-webhook:
  - apiVersion: v2
    appVersion: 1.3.2
    created: "2023-07-07T09:42:00.999116402+02:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: 42035b2472ac870c798100fc0f79ee63a3bbee517b62910c964ae153892b0f43
    home: https://runnerm.github.io/simply-dns-webhook/README.md
    icon: https://user-images.githubusercontent.com/51089137/195098737-fc66a30f-6174-45ed-b995-3f2689dafd2e.png
    maintainers:
    - email: pentek.marci@gmail.com
      name: runnerm
      url: https://github.com/runnerm
    name: simply-dns-webhook
    sources:
    - https://github.com/RunnerM/simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.3.2.tgz
    version: 1.3.2
  - apiVersion: v2
    appVersion: 1.3.1
    created: "2023-06-20T09:46:15.6371905Z"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: 81c4cbd15d8535295ac91577d2453d18cad166880fa46d3792607b751e233438
    home: https://runnerm.github.io/simply-dns-webhook/README.md
    icon: https://user-images.githubusercontent.com/51089137/195098737-fc66a30f-6174-45ed-b995-3f2689dafd2e.png
    maintainers:
    - email: pentek.marci@gmail.com
      name: runnerm
      url: https://github.com/runnerm
    name: simply-dns-webhook
    sources:
    - https://github.com/RunnerM/simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.3.1.tgz
    version: 1.3.1
  - apiVersion: v2
    appVersion: 1.3.0
    created: "2023-05-26T10:25:18.29744494+02:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: c743ade64f435c0739e9adb2420308b4797cda7ac7ecfa02edb239e8b7fd7e3e
    home: https://runnerm.github.io/simply-dns-webhook/README.md
    icon: https://user-images.githubusercontent.com/51089137/195098737-fc66a30f-6174-45ed-b995-3f2689dafd2e.png
    maintainers:
    - email: pentek.marci@gmail.com
      name: runnerm
      url: https://github.com/runnerm
    name: simply-dns-webhook
    sources:
    - https://github.com/RunnerM/simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.3.0.tgz
    version: 1.3.0
  - apiVersion: v2
    appVersion: 1.2.1
    created: "2023-05-26T10:25:18.297194715+02:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: b16d8e96dcccdfaef2f8aa53a184534528be58175b3d528c3defa2bf52ad45f2
    home: https://runnerm.github.io/simply-dns-webhook/README.md
    icon: https://user-images.githubusercontent.com/51089137/195098737-fc66a30f-6174-45ed-b995-3f2689dafd2e.png
    maintainers:
    - email: pentek.marci@gmail.com
      name: runnerm
      url: https://github.com/runnerm
    name: simply-dns-webhook
    sources:
    - https://github.com/RunnerM/simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.2.1.tgz
    version: 1.2.1
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2023-04-05T12:57:09.492649921+02:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: c6e0b2c00eb84a65fd78a47e0c3119ef03597534018789ee20d1c02a547d2866
    icon: https://user-images.githubusercontent.com/51089137/195098737-fc66a30f-6174-45ed-b995-3f2689dafd2e.png
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 1.1.3
    created: "2023-04-05T12:57:09.492446528+02:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: fe67f14159cdaab838f4d12e517163064cf698d4de3a5331eb46cb5dc32ef81f
    icon: https://user-images.githubusercontent.com/51089137/195098737-fc66a30f-6174-45ed-b995-3f2689dafd2e.png
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.1.3.tgz
    version: 1.1.3
  - apiVersion: v2
    appVersion: 1.1.2
    created: "2023-04-05T12:57:09.49224597+02:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: 07e4ae8bbdc8fcfedcdf03ba835dc8f4a3c3b58226318f365b5802b3d81e8e82
    icon: https://user-images.githubusercontent.com/51089137/195098737-fc66a30f-6174-45ed-b995-3f2689dafd2e.png
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.1.2.tgz
    version: 1.1.2
  - apiVersion: v2
    appVersion: 1.1.1
    created: "2023-04-05T12:57:09.492039271+02:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: ac102e2c99bdbc2cc4c2522043b729cd85783409b6876db33d42cb7dddbb1d18
    icon: https://user-images.githubusercontent.com/51089137/195098737-fc66a30f-6174-45ed-b995-3f2689dafd2e.png
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.1.1.tgz
    version: 1.1.1
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2023-04-05T12:57:09.491826069+02:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: f8957d73529e51e1acd498c0c89bdbe431f9de851fb9f0a6524253da560f597e
    icon: https://user-images.githubusercontent.com/51089137/195098737-fc66a30f-6174-45ed-b995-3f2689dafd2e.png
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 1.0.3
    created: "2023-04-05T12:57:09.491632153+02:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: 4e6498f38ca6a629c48570d4e8f764324506b4ca9b67c04a3aa5537f0c0ec343
    icon: https://user-images.githubusercontent.com/51089137/195098737-fc66a30f-6174-45ed-b995-3f2689dafd2e.png
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-04-05T12:57:09.491437727+02:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: cf3be17f6203ce9429c2646c5e674a1b23d9749094006f270b3fff19fb237a42
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-04-05T12:57:09.491243541+02:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: 569f661f2eacc3fef309d407b772627319e45017e295545c66aa33d5b338e7d9
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-04-05T12:57:09.491032333+02:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: 334532be5c3e14f9155ff0afaacfb8227a2e2589402c41b6d3fe262d26467fb4
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.0.0.tgz
    version: 1.0.0
generated: "2023-06-20T09:46:15.6328509Z"
